file_endpoint:
  controller: Greendot\ImagePullerClient\Controller\Api::saveImage
  path:       "%image_puller_client.endpoint%/save"

validate:
  controller: Greendot\ImagePullerClient\Controller\Api::validate
  path: "%image_puller_client.endpoint%/validate"