services:
  _defaults:
    autowire: true
    autoconfigure: true

  Greendot\ImagePullerClient\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'


  Greendot\ImagePullerClient\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']