services:

  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    bind:
      $jwtPass:     '%image_puller_client.jwt_pass%'
      $jwtUser:     '%image_puller_client.jwt_user%'
      $src:         '%image_puller_client.src%'
      $projectRoot: '%kernel.project_dir%'
      $endpoint:    '%image_puller_client.endpoint'

  Greendot\ImagePullerClient\:
    resource: '../../../src'
    exclude:
      - '../../../src/DependencyInjection/'
      - '../../../src/Entity/'
      - '../../../src/Kernel.php'
      - '../../../src/Tests/'

  Greendot\ImagePullerClient\Controller\:
    resource: '../../../src/Controller/'
    tags: ['controller.service_arguments']
